In [1]:
import numpy as np
def _init_pop_gen(n, m):
    grid=[]
    row_init=np.random.randint(2, size=m)
    grid=row_init
    i=1
    while i<n:
        row=np.random.randint(2, size=m)
        grid=np.vstack((grid,row))
        grid=np.unique(grid,axis=0)
        i=np.size(grid,0)
    return grid

In [2]:
def _check(grid,value,sum):
    grid=np.unique(grid,axis=0)
    (n,m)=grid.shape
    fitness=_fitness(grid,value)
    count=0
    for i in range(n):
        if (fitness[i]>sum):
            grid=np.delete(grid, i-count, 0)
            count+=1
    return grid

In [3]:
def _fitness(grid,value):
    (n,m)=grid.shape
    fitness=[]
    for i in range(n):
        fitness.append(0)
        for j in range(m):
            fitness[i]+=grid[i][j]*value[j]
    return fitness

In [4]:
def _selection(n,fitness):
    sorted=np.sort(fitness)[::-1]
    indices=np.argsort(fitness)[::-1]
    cf=[]
    cf.append(0)
    cf[0]=sorted[0]
    for i in range(1,n):
        cf.append(0)
        cf[i]=cf[i-1]+sorted[i]
    num=np.random.randint(cf[n-1])
    i=0
    while (cf[i]<num):
        i=i+1
    return indices[i]

In [5]:
def _crossover(cor,grid,value):
    (n,m)=grid.shape
    no_co=(cor*n*m)//100
    for i in range(no_co):
        fitness=_fitness(grid,value)
        p=np.random.randint(0,m)
        while True:
            c1=_selection(n,fitness)
            c2=_selection(n,fitness)
            if (c1!=c2):
                break
        child1=np.hstack((grid[c1,0:p], grid[c2,p:m]))
        child2=np.hstack((grid[c2,0:p],grid[c1,p:m]))
        grid=np.vstack((grid,child1))
        grid=np.vstack((grid,child2))
        n=np.size(grid,0)
    return grid

In [6]:
def _mutation(mr,grid,value):
    (n,m)=grid.shape
    no_mu=(mr*n*m)//100
    for i in range(no_mu):
        fitness=_fitness(grid,value)
        p=np.random.randint(0,m-1)
        c=_selection(n,fitness)
        if (grid[c,p]==1):
            grid[c,p]=0
        else:
            grid[c,p]=1
    return grid

In [12]:
m=8#int(input('Enter the number of cells in Set\t:'))
n=int(input('Enter number of chromosomes\t:'))
grid=_init_pop_gen(n,m)
value=[15,22,14,26,32,9,16,8]
#for i in range(m):
#    val=int(input('\nEnter Value['+str(i+1)+']\t:'))
#    value.append(val)

sum=53#int(input('\nEnter target sum of Subset!\n'))
grid=_check(grid,value,sum)
cor=10#int(input('\nEnter crossover rate:\t'))
mr=1#int(input('\nEnter mutation rate:\t'))
subset=[]
print('\nShape:\t',grid.shape)
no_gen=int(input('\n\nEnter no of Generations:\t'))
gen=0

while(gen<no_gen):
    grid=_crossover(cor,grid,value)
    grid=_check(grid,value,sum)
    grid=_mutation(mr,grid,value)
    grid=_check(grid,value,sum)
    fitness=_fitness(grid,value)
    n=np.size(grid,0)
    for i in range(n):
        if (fitness[i]==sum):
            subset.append(grid[i])
    gen+=1
subset=np.unique(subset,axis=0)
print('\n\nGiven Set:\t',value)
print('\n\nSum:\t',sum)
print('\n\nSubsets\n',subset)

Enter number of chromosomes	:50

Shape:	 (8, 8)


Enter no of Generations:	20


Given Set:	 [15, 22, 14, 26, 32, 9, 16, 8]


Sum:	 53


Subsets
 [[0 1 1 0 0 1 0 1]
 [1 0 1 0 0 0 1 1]
 [1 1 0 0 0 0 1 0]]
